# Generated by Django 3.1 on 2021-08-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favoriteposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritePosts',
        ),
    ]
